// Generated by view binder compiler. Do not edit!
package com.tm.chatsapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.tm.chatsapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RowConversationBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final TextView lastMsg;

  @NonNull
  public final TextView msgTime;

  @NonNull
  public final TextView username;

  private RowConversationBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView imageView2,
      @NonNull TextView lastMsg, @NonNull TextView msgTime, @NonNull TextView username) {
    this.rootView = rootView;
    this.imageView2 = imageView2;
    this.lastMsg = lastMsg;
    this.msgTime = msgTime;
    this.username = username;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RowConversationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RowConversationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.row_conversation, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RowConversationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.lastMsg;
      TextView lastMsg = ViewBindings.findChildViewById(rootView, id);
      if (lastMsg == null) {
        break missingId;
      }

      id = R.id.msgTime;
      TextView msgTime = ViewBindings.findChildViewById(rootView, id);
      if (msgTime == null) {
        break missingId;
      }

      id = R.id.username;
      TextView username = ViewBindings.findChildViewById(rootView, id);
      if (username == null) {
        break missingId;
      }

      return new RowConversationBinding((ConstraintLayout) rootView, imageView2, lastMsg, msgTime,
          username);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
